Update to use config file
ActioFRM/rule-003 pull request #21
Opened 2021-09-14 13:06 UTC by johanfol

2021-09-15 07:57 UTC, joeygoksu requested changes
Overall is good! Just a few comments

2021-09-15 07:57 UTC, joeygoksu commented on __tests__/unit/logic.service.test.ts
> +  config.apmLogging = false;
You can set these environment variables in jest config. Otherwise, the test case would be not accurate.
(In jest.config.ts, there is a field named "setupFiles".)

2021-09-15 07:57 UTC, joeygoksu commented on __tests__/unit/logic.service.test.ts
> +      expect(result.result).toBeFalsy();
I see only .toBeFalsy() - (means failed cases). Don't we need to test successful test cases?

2021-09-15 07:57 UTC, joeygoksu commented on jest.config.ts
> +  // collectCoverageFrom: ['src/**/*.{ts,js}', '!src/**/*.d.ts'],
I think this line should stay there instead of collecting coverage from specific files.
Otherwise, when we add new files, the coverage would not change.
Suggestion/idea: using ignore files field for coverage?

2021-09-15 07:57 UTC, joeygoksu commented on package.json
>      "start": "node build/index",
Can we update/sync these script lines with TADproc?
There were some problems but I have fixed them in TADProc branch.
For example, we don't need to pass environment variables to nodemon.

2021-09-15 07:57 UTC, joeygoksu commented on package.json
> +    "@types/axios": "^0.14.0",
We don't need axios type in dependencies. It should be in devDependencies.

2021-09-15 07:57 UTC, joeygoksu commented on package.json
>      "swagger2-koa": "^3.0.0",
There are some @types missing in this file.
Eg. @types/elastic-apm-node

2021-09-15 07:57 UTC, joeygoksu commented on src/clients/arango-client.service.ts
> +  getRuleConfig(ruleId: string): Promise<any> {
I like that 👍

2021-09-15 07:57 UTC, joeygoksu commented on src/config.ts
> +  viewName: <string>process.env.VIEW_NAME,
viewName or collectionName? Which one would be better? After discussion, I can update other repos if necessary.

2021-09-15 12:02 UTC, johanfol commented on __tests__/unit/logic.service.test.ts
> +      expect(result.result).toBeFalsy();
There is only one test required for Truthy, as the account is dormant, or it isn't. In case it's not dormant, eg, False, there are many different scenarios, where the code has many branches. This is why there is so many Falsy tests.

2021-09-15 12:32 UTC, johanfol commented on jest.config.ts
> +  // collectCoverageFrom: ['src/**/*.{ts,js}', '!src/**/*.d.ts'],
I tried with Ignore list, but the ignore list is just way longer than the allow list. Remember once we have the libraries, most of the addition files should fall away, and we'd realistically only want to test one File - the Logic.ts file. So I'm happy with the approach of only testing one file...

2021-09-15 12:34 UTC, johanfol commented on src/config.ts
> +  viewName: <string>process.env.VIEW_NAME,
It depends on what it is. For this rule I actually created a "View" inside of ArangoDB - instead of using a Graph or the Collection directly. So viewName = the name of the View.

2021-09-15 13:25 UTC, joeygoksu commented on src/config.ts
> +  viewName: <string>process.env.VIEW_NAME,
Ah ok - I didn't know that. That's cool then 👍

2021-09-20 07:32 UTC, johanfol commented on package.json
>      "swagger2-koa": "^3.0.0",
Why would we need @types ? If it's not needed, since our interaction with APM is so limited, not sure why we would HAVE to install them?

2021-09-21 07:57 UTC, joeygoksu requested changes

2021-09-21 07:57 UTC, joeygoksu commented on package.json
>      "cleanup": "rem -rf build template jest.config.js jest.config.js.map node_modules yarn.lock",
```suggestion
    "cleanup": "rm -rf build template jest.config.js jest.config.js.map node_modules yarn.lock",
```

2021-09-21 07:58 UTC, joeygoksu commented
package-lock.json needs to be replaced with yarn.lock  @johanfol

2021-09-23 10:36 UTC, joeygoksu approved these changes
LGTM! 🎉

2021-09-27 07:55 UTC, merged