add 1.1 version for rule 003
ActioFRM/rule-003 pull request #32
Opened 2022-01-17 12:36 UTC by uche-lextego

2022-01-17 15:09 UTC, johanfol approved these changes

2022-01-17 15:38 UTC, vorsterk requested changes
Looks good , Just remove the credentials from the docker file

2022-01-17 18:05 UTC, uche-lextego commented
> Looks good , Just remove the credentials from the docker file

Thanks, fixed

2022-01-18 06:09 UTC, vorsterk approved these changes
looks good

2022-01-21 14:34 UTC, merged