Update rule processors to make use of CFG for config
ActioFRM/rule-003 pull request #36
Opened 2022-02-22 08:48 UTC by uche-lextego

2022-02-25 10:41 UTC, johanfol requested changes

2022-02-25 10:41 UTC, johanfol commented on src/services/logic.service.ts
>      cfg: `${config.ruleVersion}`,
```suggestion
    cfg: `${ruleResult.cfg}`,
```

2022-02-28 06:22 UTC, vorsterk approved these changes
Looks good

2022-03-04 07:23 UTC, johanfol approved these changes

2022-03-08 03:39 UTC, merged